# The Site Configuration
theme: jekyll-theme-chirpy

# Language and timezone settings
lang: en
timezone: # Set your timezone, e.g., "America/New_York"

# Site metadata
title: FuzzBlackbox
tagline: Learn. Share. Learn Again.
description: >-
  Welcome to FuzzBlackbox, your resource for knowledge and innovation.
url: "" # Add your site URL without trailing slash, e.g., "https://username.github.io"

# Social media and contact information
github:
  username: fuzzblackbox

twitter:
  username: twitter_username

social:
  name: Fuzzblackbox
  email: stillnot
  links:
    - https://twitter.com/username
    - https://github.com/username
    # Add more links if necessary

# Webmaster tools verification
webmaster_verifications:
  google: # Add your Google verification code
  bing: # Add your Bing verification code

# Analytics
analytics:
  google:
    id: # Your Google Analytics ID

# Page views settings
pageviews:
  provider: goatcounter # Supported provider (only "goatcounter" is valid)

# Appearance settings
theme_mode: dark # Choose between "light", "dark", or leave empty for system default

# Media settings
cdn: # Add your CDN URL if used
avatar: /assets/images/blackbox.jpg
 #avatar: # Add the avatar image URL or leave blank
social_preview_image: # Add a URL for the site's social preview image

# Table of contents global setting
toc: true

# Comments
comments:
  provider: # Uncomment and set a provider if needed [disqus | utterances | giscus]
  disqus:
    shortname: # Add Disqus shortname

# Self-hosted static assets
assets:
  self_host:
    enabled: false

# Progressive Web App (PWA) settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # Add paths you want to exclude from caching

# Pagination
paginate: 10

# Base URL of your site
baseurl: ""

# Syntax highlighting and kramdown settings
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: true
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: "" # Applies to all files
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass
sass:
  style: compressed

# HTML compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Files to exclude from the build
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

# Future posts settings
future: true

# Jekyll Archives Plugin Settings
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
